# Generated by Django 3.2.7 on 2021-09-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joining_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
