# Generated by Django 3.2.7 on 2021-09-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customer_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
