# Generated by Django 3.2.7 on 2021-09-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_customer_joining_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='amount',
            new_name='recuring_amount',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
