# Generated by Django 3.2.7 on 2021-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='generate_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('paid', 'Paid')], max_length=10, null=True),
        ),
    ]
