# Generated by Django 3.2.7 on 2021-09-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20210927_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
