# Generated by Django 3.2.7 on 2021-09-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_bill_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/{name}'),
        ),
    ]
