# Generated by Django 3.2.7 on 2021-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
