# Generated by Django 3.2.7 on 2021-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_customer_next_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
