# Generated by Django 3.2.7 on 2021-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_bill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
