# Generated by Django 3.2.7 on 2021-09-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_customer_eligible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='next_payment',
        ),
        migrations.AddField(
            model_name='customer',
            name='next_payment_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_payment_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_payment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
