# Generated by Django 3.2.7 on 2021-09-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20210928_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='next_payment_date',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_payment_month',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
