# Generated by Django 3.2.7 on 2021-09-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20210928_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='period',
            field=models.IntegerField(choices=[('1', 'Monthly'), ('3', 'Quaterly'), ('6', 'Half Yearly'), ('12', 'Yearly')]),
        ),
    ]
