# Generated by Django 3.2.7 on 2021-09-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_customer_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recuring_time',
            field=models.IntegerField(choices=[('1', 'Monthly'), ('3', 'Quaterly'), ('6', 'Half Yearly'), ('12', 'Yearly')]),
        ),
    ]
