# Generated by Django 3.2.7 on 2021-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20210928_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recuring_time',
            field=models.IntegerField(),
        ),
    ]
