# Generated by Django 3.2.7 on 2021-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_customer_recuring_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='staus',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('disable', 'Disable')], max_length=10, null=True),
        ),
    ]
