# Generated by Django 3.2.7 on 2021-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_customer_staus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='staus',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=10, null=True),
        ),
    ]
