# Generated by Django 3.2.7 on 2021-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_customer_staus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joining_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
