# Generated by Django 3.2.7 on 2021-11-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customer'),
        ),
    ]
