# Generated by Django 3.2.4 on 2021-09-21 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(default='', max_length=30)),
                ('assign_to', models.CharField(default='', max_length=30)),
                ('mobile_no', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('fresh', 'Fresh'), ('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='fresh', max_length=20)),
                ('closed_or_pending', models.CharField(blank=True, choices=[('low_budget', 'Low Budget'), ('we_cant_do', 'We Cant Do'), ('client', 'Client Converted')], max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='lead/images')),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='followup/files')),
                ('image', models.ImageField(blank=True, null=True, upload_to='followup/images')),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('f_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='Agents/images')),
                ('organization', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='home.organization')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
