# Generated by Django 3.2.4 on 2021-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_followup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='followup/files'),
        ),
    ]
