# Generated by Django 3.2.4 on 2021-09-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_followup_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='file',
            new_name='follow_file',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='image',
            new_name='follow_image',
        ),
    ]
