# Generated by Django 3.2.4 on 2021-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210923_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
