# Generated by Django 3.2.4 on 2021-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210923_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_file',
            field=models.FileField(blank=True, null=True, upload_to='followup'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_image',
            field=models.ImageField(blank=True, null=True, upload_to='followup'),
        ),
    ]
